##Spring Configuration
server:
  port: 5000
spring:
  application:
    name: "RetoGoty"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: /h2
  profiles:
    include:
